### ISSUE TITLE
Non-double roll misinterpreted as half-move in some scenarios

### ISSUE THREAD

**Issue by deprus** [carsten-wenderdel/wildbg#29]
For some non-double rolls with only one valid move, the engine incorrectly restricts the move to the closest checker using the larger die, omitting the remaining die move. The engine should apply both dice by moving the closest checker with the larger die, then moving another checker with the remaining die. API URL for attached screenshot: https://wildbg.shuttleapp.rs/move?die1=6&die2=2&p1=0&p2=0&p4=-2&p6=13&p8=1&p16=-2&p18=-3&p19=-4&p20=-4&p24=1

![Screenshot 2024-10-30 192541](https://github.com/user-attachments/assets/78dc2f43-74d5-4864-9737-88a563f20828)

**Comment by carsten-wenderdel** [comment]
Yes, instead of moving `8-2` only, `24-22` should be moved as well. This bug was already in the releases `0.1` and `0.2`. Thanks a lot for raising this issue!

I've fixed the bug today. After doing that I found, that the whole code part is not really needed at all and can be done in an easier way. In the end I deleted about 50 lines of code.
